export const TOURNAMENT_TOTAL_MATCHES = 104
export const TOURNAMENT_TOTAL_TEAMS = 48
export const MATCH_EXACT_POINTS = 3
export const SPECIAL_BETS_TOTAL_POINTS = 50

export const TOURNAMENT_TOTAL_POINTS =
  TOURNAMENT_TOTAL_MATCHES * MATCH_EXACT_POINTS + SPECIAL_BETS_TOTAL_POINTS
