import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { SCORING } from '@/lib/daily-prode/scoring'

const rules = [
  ['Participación', 'Una entrada por persona, sala y jornada. Podés participar en varias salas. Cada sala tiene participantes y pozo propios; no hay segundo ni tercer premio. Si hay empate en el primer puesto, el pozo demo se divide entre quienes empatan. No hay pagos reales implementados.'],
  ['Fútbol', `Marcador exacto a 90 minutos: ${SCORING.football.exact} puntos. Resultado general local/empate/visitante: ${SCORING.football.general}. Incorrecto: ${SCORING.football.wrong}. En eliminación se separan 90 minutos, alargue, penales y clasificado; el criterio de clasificado sigue pendiente y los penales no forman parte del exacto a 90.`],
  ['Tenis', `Sets exactos: ${SCORING.tennis.exact} puntos. Ganador correcto con sets distintos: ${SCORING.tennis.winner}. Ganador incorrecto: ${SCORING.tennis.wrong}. Se valida el formato mejor de 3 o mejor de 5 para evitar resultados imposibles.`],
  ['Boxeo', `Ganador + KO/TKO + round exacto: ${SCORING.boxing.exact}. Ganador + método: ${SCORING.boxing.method}. Ganador + decisión/no KO: ${SCORING.boxing.decision}. Solo ganador: ${SCORING.boxing.winner}. Incorrecto: ${SCORING.boxing.wrong}. Empate, no contest y anulación siguen pendientes.`],
  ['MMA próximamente', 'MMA todavía no publica eventos ni puntajes. Requiere proveedor, tipos de resultado, método, round, decisión, empate, no contest y reglas aprobadas.'],
]
export default function DailyRulesPage() { return <main className="mx-auto max-w-[1100px] px-4 py-12 pb-28"><p className="font-mono text-[11px] font-extrabold uppercase tracking-[.15em] text-mint">REGLAS DEL PRODE DIARIO</p><h1 className="mt-2 font-display text-[clamp(44px,8vw,78px)] uppercase leading-[.9]">Reglas para <em className="text-orange">la jornada.</em></h1><p className="mt-5 max-w-[650px] text-[15px] font-semibold leading-relaxed text-muted">Las jornadas diarias usan datos demo manuales y no están conectadas a pagos ni a un proveedor deportivo real.</p><section className="mt-10 grid gap-3 min-[700px]:grid-cols-2">{rules.map(([title, text]) => <article key={title} className="rounded-lg border border-white/10 bg-panel p-5"><p className="font-mono text-[10px] font-extrabold uppercase tracking-[.12em] text-orange">{title}</p><p className="mt-3 text-sm font-medium leading-relaxed text-[#d5d5d5]">{text}</p></article>)}</section><Link href="/diario" className="mt-8 inline-flex min-h-11 items-center gap-2 rounded-md bg-orange px-4 text-sm font-extrabold text-[#0a0a0a]">Ir al Prode diario <ArrowRight size={16} /></Link></main> }
