'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, CalendarDays, Trophy } from 'lucide-react'
import { DailyVisualAtmosphere } from '@/components/DailyVisualAtmosphere'
import { DailyJourneySelector } from '@/components/DailyJourneySelector'
import { journeyDate } from '@/lib/daily-prode/journey'

type View = 'my-prode' | 'ranking'

export function DailyDestinationPage({ view }: { view: View }) {
  const isMine = view === 'my-prode'
  const [date, setDate] = useState(journeyDate())
  return <div className="relative isolate min-h-full overflow-hidden bg-bg text-white"><DailyVisualAtmosphere /><main className="relative z-10 mx-auto w-full max-w-[1200px] px-4 py-10 pb-28 min-[768px]:px-6"><p className="font-mono text-[11px] font-extrabold uppercase tracking-[.15em] text-mint">{isMine ? 'Mi Prode diario' : 'Ranking diario'}</p><h1 className="mt-2 font-display text-[clamp(42px,8vw,78px)] uppercase leading-[.9]">{isMine ? <>Tu jornada <em className="text-orange">en orden.</em></> : <>La sala <em className="text-orange">en orden.</em></>}</h1><p className="mt-5 max-w-2xl text-[15px] font-semibold leading-relaxed text-muted">{isMine ? 'Tus pronósticos diarios se organizan por jornada y sala. No se incluyen predicciones de competencias históricas.' : 'La clasificación se calcula por jornada y sala; no reutiliza resultados ni participantes históricos.'}</p><div className="mt-7 max-w-md rounded-lg border border-white/10 bg-black/75 p-4"><DailyJourneySelector value={date} onChange={setDate} /></div>{isMine ? <MyProdeEmpty /> : <RankingEmpty />}<div className="mt-8 flex flex-wrap gap-3"><Link href="/" className="inline-flex min-h-11 items-center gap-2 rounded-md bg-orange px-4 text-sm font-extrabold text-[#0a0a0a]">Ver agenda <ArrowRight size={16} /></Link><Link href={isMine ? '/ranking' : '/mi-prode'} className="inline-flex min-h-11 items-center gap-2 rounded-md border border-white/15 bg-black/70 px-4 text-sm font-extrabold">{isMine ? 'Ver ranking' : 'Ver mi Prode'} <ArrowRight size={16} /></Link></div></main></div>
}

function MyProdeEmpty() { return <section className="mt-8"><div className="grid gap-2 min-[560px]:grid-cols-2 min-[900px]:grid-cols-4"><Card label="Pronósticos futuros" value="0" detail="Sin jornada activa" /><Card label="Eventos pendientes" value="0" detail="Sin eventos verificados" /><Card label="Acertados / fallados" value="0 / 0" detail="Sin resultados diarios" /><Card label="Puntos obtenidos" value="0" detail="0 pendientes" /></div><article className="mt-5 rounded-lg border border-dashed border-white/15 bg-black/60 p-6"><div className="flex items-start gap-3"><CalendarDays className="mt-0.5 shrink-0 text-orange" size={22} /><div><h2 className="font-display text-3xl uppercase">Todavía no hay participación diaria</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted">No hay sala, importe ni eventos verificados activos para tus pronósticos. Cuando se publique una jornada autorizada, esta vista mostrará cada evento, estado, pronóstico, puntos obtenidos y puntos pendientes.</p></div></div></article></section> }
function RankingEmpty() { return <section className="mt-8"><div className="grid gap-2 min-[600px]:grid-cols-3"><Card label="Sala seleccionada" value="—" detail="Sin sala activa" /><Card label="Pozo estimado" value="—" detail="Sin importe publicado" /><Card label="Estado" value="En espera" detail="Sin jornada verificada" /></div><article className="mt-5 rounded-lg border border-dashed border-white/15 bg-black/60 p-6"><div className="flex items-start gap-3"><Trophy className="mt-0.5 shrink-0 text-orange" size={22} /><div><h2 className="font-display text-3xl uppercase">No hay ranking diario activo</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted">El ranking aparecerá al publicarse una jornada con sala y eventos verificados. Los empates del primer puesto se resolverán según las reglas diarias vigentes.</p></div></div></article></section> }
function Card({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="min-h-28 rounded-lg border border-white/10 bg-black/80 p-4"><p className="font-mono text-[10px] font-extrabold uppercase tracking-[.1em] text-muted">{label}</p><strong className="mt-3 block font-display text-3xl leading-none">{value}</strong><small className="mt-3 block text-[11px] font-semibold text-muted">{detail}</small></article> }
